# -*- coding: utf-8 -*-
"""AI SATPLAN TESTING

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cf8GXgmkV-6AsW0RwbUVAzL44NAAULSr
"""

from google.colab import drive
drive.mount('/content/gdrive/')

cd gdrive/

cd MyDrive/

cd 'AI Satplan'/

ls

cat 'blocks2.dat'

cat 'iter2.dat'

!python Main.py '3 blocks.dat'

cat sat2.dat

cat valid.dat

cat dimacs2.dat

cat dimacs.dat

ls

!python Main.py '3 blocks.dat''