# -*- coding: utf-8 -*-
"""sat_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16VqdFtj5gQbX09oiQ2_RMfrgDXLhZz81
"""

from google.colab import drive
drive.mount('/content/drive/',force_remount=True)

cd /content/drive/MyDrive/AI Satplan/SatSolver

pwd

cat 3 blocks.dat

!pip install git+https://github.com/remykarem/py2pddl#egg=py2pddl

cd /content/drive/MyDrive/ai/py2pddl/pddl/

!python -m pddl.init logistics.py

!python -m py2pddl.init aircargo.py

!python /content/drive/MyDrive/ai/py2pddl/pddl/logistics.py transport.dat













cd /content/drive/MyDrive/ai/py2pddl

!pip install udacity-pa

!pip install requirements.txt



